.PHONY: clean All

All:
	@echo "----------Building project:[ simple-interest - Debug ]----------"
	@cd "simple-interest" && "$(MAKE)" -f  "simple-interest.mk"
clean:
	@echo "----------Cleaning project:[ simple-interest - Debug ]----------"
	@cd "simple-interest" && "$(MAKE)" -f  "simple-interest.mk" clean
